#ifndef SWND_VERSION_INCLUDED
#define SWND_VERSION_INCLUDED

#define MAKE_STR_HELPER(a_str) #a_str
#define MAKE_STR(a_str)        MAKE_STR_HELPER(a_str)

#define MHUD_VERSION_MAJOR 1
#define MHUD_VERSION_MINOR 1
#define MHUD_VERSION_PATCH 7
#define MHUD_VERSION_BETA  0
#define MHUD_VERSION_VERSTRING   \
    MAKE_STR(MHUD_VERSION_MAJOR) \
    "." MAKE_STR(MHUD_VERSION_MINOR) "." MAKE_STR(MHUD_VERSION_PATCH) "." MAKE_STR(MHUD_VERSION_BETA)

#endif
